title: my github page
theme: jekyll-theme-cayman
title: thetomato0s homepage
description: Bookmark this to keep an eye on my project updates!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
